name: build

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ['tip', '1.22', '1.21', '1.20', '1.19', '1.18']
    steps:
      - name: Setup Go
        if: matrix.go-version != 'tip'
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go-version }}
      - name: Setup Go tip if needed
        if: matrix.go-version == 'tip'
        run: |
          set -ex
          curl --head https://github.com/phuslu/go/releases/download/v0.0.0/gotip.linux-amd64.tar.xz
          sleep 1
          curl -LOJ https://github.com/phuslu/go/releases/download/v0.0.0/gotip.linux-amd64.tar.xz
          rm -rf /usr/local/go
          sudo tar xJf gotip.linux-amd64.tar.xz -C /usr/local
          sudo ln -sf /usr/local/go/bin/go /usr/bin/go
          go version
      - uses: actions/checkout@v4
      - name: Test
        run: go test -v -race
